language: objective-c
osx_image: xcode10
xcode_sdk: iphonesimulator12
install:
- gem install xcpretty
script:
  - set -o pipefail
  - travis_retry xcodebuild -project KRPullLoader.xcodeproj -scheme KRPullLoader -destination "platform=iOS Simulator,name=iPhone 8" build-for-testing test | xcpretty
notifications:
  email: false
